defaults:
  - scope:
      path: ""
    values:
      layout: "default"

title: Chen's Home Page
email: chen.c.aj@m.titech.ac.jp
description: > # this means to ignore newlines until "baseurl:"
  Chen Cheng's Personal Webpage
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass
